baseURL = "https://lewvii.github.io/"
title = "Lewvii's Blog"
theme = "PaperMod"

# 语言设置（可选双语）
defaultContentLanguage = "zh-cn"
[languages]
  [languages.zh-cn]
    languageCode = "zh-cn"
    languageName = "中文"
    weight = 1
  [languages.en-us]
    languageCode = "en-us"
    languageName = "English"
    weight = 2

# 输出格式
[outputs]
  home = ["HTML", "RSS"]

# PaperMod自定义参数
[params]
  # homeInfoParams 不再单独声明，直接缩进其内容
  homeInfoParams.Title = "欢迎来到Lewvii的博客"
  homeInfoParams.Content = "这是一个分享技术与生活的网站，基于Hugo搭建。"
  socialIcons = [
    {name = "github", url = "https://github.com/lewvii"},
    {name = "twitter", url = "https://twitter.com/yourhandle"}
  ]

# 导航菜单
[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 1
[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 2